export type FacturacionComprobanteOption = {
  code: string;
  description: string;
};

export const FACTURACION_FORMATOS_DESTACADOS = ['01', '03', '201', '203'] as const;

export const FACTURACION_COMPROBANTES_OPTIONS: FacturacionComprobanteOption[] = [
  { code: '01', description: 'FACTURA A' },
  { code: '02', description: 'NOTA DE DEBITO A' },
  { code: '03', description: 'NOTA DE CREDITO A' },
  { code: '04', description: 'RECIBO A' },
  { code: '05', description: 'NOTAS DE VENTA AL CONTADO A' },
  { code: '06', description: 'FACTURA B' },
  { code: '07', description: 'NOTA DE DEBITO B' },
  { code: '08', description: 'NOTA DE CREDITO B' },
  { code: '09', description: 'RECIBO B' },
  { code: '10', description: 'NOTAS DE VENTA AL CONTADO B' },
  { code: '11', description: 'FACTURA C' },
  { code: '12', description: 'NOTA DE DEBITO C' },
  { code: '13', description: 'NOTA DE CREDITO C' },
  { code: '15', description: 'RECIBO C' },
  { code: '16', description: 'NOTAS DE VENTA AL CONTADO C' },
  { code: '17', description: 'LIQUIDACION DE SERVICIOS PUBLICOS CLASE A' },
  { code: '18', description: 'LIQUIDACION DE SERVICIOS PUBLICOS CLASE B' },
  { code: '19', description: 'FACTURA POR OPERACIONES CON EL EXTERIOR' },
  { code: '20', description: 'NOTA DE DEBITO POR OPERACIONES CON EL EXTERIOR' },
  { code: '21', description: 'NOTA DE CREDITO POR OPERACIONES CON EL EXTERIOR' },
  { code: '22', description: 'FACTURA PERMISO EXPORTACION SIMPLIFICADO - DTO. 855/97' },
  { code: '23', description: 'COMPROBANTES CLASE “A” DE COMPRA PRIMARIA PARA EL SECTOR PESQUERO MARITIMO' },
  { code: '24', description: 'COMPROBANTES CLASE “A” DE CONSIGNACION PRIMARIA PARA EL SECTOR PESQUERO MARITIMO' },
  { code: '25', description: 'COMPROBANTES CLASE “B” DE COMPRA PRIMARIA PARA EL SECTOR PESQUERO MARITIMO' },
  { code: '26', description: 'COMPROBANTES CLASE “B” DE CONSIGNACION PRIMARIA PARA EL SECTOR PESQUERO MARITIMO' },
  { code: '27', description: 'LIQUIDACION UNICA COMERCIAL IMPOSITIVA CLASE A' },
  { code: '28', description: 'LIQUIDACION UNICA COMERCIAL IMPOSITIVA CLASE B' },
  { code: '29', description: 'LIQUIDACION UNICA COMERCIAL IMPOSITIVA CLASE C' },
  { code: '30', description: 'COMPROBANTE DE COMPRA DE BIENES USADOS' },
  { code: '31', description: 'MANDATO - CONSIGNACION' },
  { code: '32', description: 'COMPROBANTE DE COMPRA DE MATERIALES A RECICLAR PROVENIENTE DE RESIDUOS' },
  { code: '33', description: 'LIQUIDACION PRIMARIA DE GRANOS' },
  { code: '34', description: 'COMPROBANTES A DEL ANEXO I, APARTADO A,  INCISO F)  R.G. N°  1415' },
  { code: '35', description: 'COMPROBANTES B  DEL ANEXO I, APARTADO A, INC. F), R.G. N° 1415' },
  { code: '36', description: 'COMPROBANTES C DEL ANEXO I, APARTADO A, INC.F), R.G. N° 1415' },
  { code: '37', description: 'NOTAS DE DEBITO O DOCUMENTOS EQUIVALENTES QUE CUMPLAN CON LA R.G. N° 1415' },
  { code: '38', description: 'NOTAS DE CREDITO O DOCUMENTOS EQUIVALENTES QUE CUMPLAN CON LA R.G. N° 1415' },
  { code: '39', description: 'OTROS COMPROBANTES A QUE CUMPLEN CON LA R G  N° 1415' },
  { code: '40', description: 'OTROS COMPROBANTES B QUE CUMPLAN CON LA R.G. N° 1415' },
  { code: '41', description: 'OTROS COMPROBANTES C QUE CUMPLAN CON LA R.G. N° 1415' },
  { code: '43', description: 'NOTA DE CREDITO LIQUIDACION UNICA COMERCIAL IMPOSITIVA CLASE B' },
  { code: '44', description: 'NOTA DE CREDITO LIQUIDACION UNICA COMERCIAL IMPOSITIVA CLASE C' },
  { code: '45', description: 'NOTA DE DEBITO LIQUIDACION UNICA COMERCIAL IMPOSITIVA CLASE A' },
  { code: '46', description: 'NOTA DE DEBITO LIQUIDACION UNICA COMERCIAL IMPOSITIVA CLASE B' },
  { code: '47', description: 'NOTA DE DEBITO LIQUIDACION UNICA COMERCIAL IMPOSITIVA CLASE C' },
  { code: '48', description: 'NOTA DE CREDITO LIQUIDACION UNICA COMERCIAL IMPOSITIVA CLASE A' },
  { code: '49', description: 'COMPROBANTES DE COMPRA DE BIENES USADOS NO REGISTRABLES A CONSUMIDORES FINALES' },
  { code: '51', description: 'FACTURA A CON LEYENDA “OPERACIÓN SUJETA A RETENCIÓN”' },
  { code: '52', description: 'NOTA DE DEBITO A CON LEYENDA “OPERACIÓN SUJETA A RETENCIÓN”' },
  { code: '53', description: 'NOTA DE CREDITO A CON LEYENDA “OPERACIÓN SUJETA A RETENCIÓN”' },
  { code: '54', description: 'RECIBO A CON LEYENDA “OPERACIÓN SUJETA A RETENCIÓN”' },
  { code: '55', description: 'NOTAS DE VENTA AL CONTADO A CON LEYENDA “OPERACIÓN SUJETA A RETENCIÓN”' },
  { code: '56', description: 'COMPROBANTES A CON LEYENDA “OPERACIÓN SUJETA A RETENCIÓN” DEL ANEXO I, APARTADO A, INC. F), R.G. N° 1.415' },
  { code: '57', description: 'OTROS COMPROBANTES A CON LEYENDA “OPERACIÓN SUJETA A RETENCIÓN”QUE CUMPLAN CON LA R.G. N° 1.415' },
  { code: '58', description: 'CUENTA DE VENTA Y LIQUIDO PRODUCTO A CON LEYENDA “OPERACIÓN SUJETA A RETENCIÓN”' },
  { code: '59', description: 'LIQUIDACION A CON LEYENDA “OPERACIÓN SUJETA A RETENCIÓN”' },
  { code: '60', description: 'CUENTAS DE VENTA Y LIQUIDO PRODUCTO A' },
  { code: '61', description: 'CUENTAS DE VENTA Y LIQUIDO PRODUCTO B' },
  { code: '63', description: 'LIQUIDACIONES A' },
  { code: '64', description: 'LIQUIDACIONES B' },
  { code: '66', description: 'DESPACHO DE IMPORTACION' },
  { code: '80', description: 'INFORME DIARIO DE CIERRE (ZETA) - CONTROLADORES FISCALES (*)' },
  { code: '81', description: 'TIQUE FACTURA A (*)' },
  { code: '82', description: 'TIQUE FACTURA B (*)' },
  { code: '83', description: 'TIQUE (*)' },
  { code: '88', description: 'REMITO ELECTRONICO' },
  { code: '89', description: 'RESUMEN DE DATOS' },
  { code: '90', description: 'OTROS COMPROBANTES - DOCUMENTOS EXCEPTUADOS - NOTAS DE CREDITO' },
  { code: '91', description: 'REMITOS R' },
  { code: '99', description: 'OTROS COMPROBANTES QUE NO CUMPLEN O ESTÁN EXCEPTUADOS DE LA R.G. 1415 Y SUS MODIF' },
  { code: '109', description: 'TIQUE C' },
  { code: '110', description: 'TIQUE NOTA DE CREDITO (*)' },
  { code: '111', description: 'TIQUE FACTURA C (*)' },
  { code: '112', description: 'TIQUE NOTA DE CREDITO A (*)' },
  { code: '113', description: 'TIQUE NOTA DE CREDITO B (*)' },
  { code: '114', description: 'TIQUE NOTA DE CREDITO C (*)' },
  { code: '115', description: 'TIQUE NOTA DE DEBITO A (*)' },
  { code: '116', description: 'TIQUE NOTA DE DEBITO B (*)' },
  { code: '117', description: 'TIQUE NOTA DE DEBITO C (*)' },
  { code: '201', description: 'FACTURA DE CRÉDITO ELECTRÓNICA MiPyMEs (FCE) A' },
  { code: '202', description: 'NOTA DE DEBITO ELECTRÓNICA MiPyMEs (FCE) A' },
  { code: '203', description: 'NOTA DE CREDITO ELECTRÓNICA MiPyMEs (FCE) A' },
  { code: '206', description: 'FACTURA DE CRÉDITO ELECTRÓNICA MiPyMEs (FCE) B' },
  { code: '207', description: 'NOTA DE DEBITO ELECTRÓNICA MiPyMEs (FCE) B' },
  { code: '208', description: 'NOTA DE CREDITO ELECTRÓNICA MiPyMEs (FCE) B' },
  { code: '211', description: 'FACTURA DE CRÉDITO ELECTRÓNICA MiPyMEs (FCE) C' },
  { code: '212', description: 'NOTA DE DEBITO ELECTRÓNICA MiPyMEs (FCE) C' },
  { code: '213', description: 'NOTA DE CREDITO ELECTRÓNICA MiPyMEs (FCE) C' },
  { code: '331', description: 'LIQUIDACION SECUNDARIA DE GRANOS' },
  { code: '332', description: 'CERTIFICACION ELECTRONICA (GRANOS)' },
  { code: '991', description: 'REMITO ELECTRÓNICO DE TABACO EN HEBRA' },
  { code: '992', description: 'RESUMEN DE DATOS DE TABACO EN HEBRA' },
  { code: '993', description: 'REMITO ELECTRÓNICO HARINERO - AUTOMOTOR' },
  { code: '994', description: 'REMITO ELECTRÓNICO HARINERO - FERROVIARIO' },
  { code: '995', description: 'REMITO ELECTRÓNICO CÁRNICO' },
  { code: '997', description: 'Remito Electrónico para Azúcar, Alcohol y Subproductos -Mercado Interno-' },
  { code: '998', description: 'Remito Electrónico para Azúcar, Alcohol y Subproductos -Exportación-' },
];
